# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bKriging <- function(samples, rtargets, tarStr, paras, model = "exponential") {
    .Call('_sptemUS_bKriging', PACKAGE = 'sptemUS', samples, rtargets, tarStr, paras, model)
}

noweiAvg <- function(path, preStr = "preno2", idStr = "id", dateStr = "s_date") {
    .Call('_sptemUS_noweiAvg', PACKAGE = 'sptemUS', path, preStr, idStr, dateStr)
}

rcpp_hello <- function() {
    .Call('_sptemUS_rcpp_hello', PACKAGE = 'sptemUS')
}

weightedstat <- function(path, modelpath, metric = "r2", preStr = "preno2", idStr = "id", dateStr = "s_date") {
    .Call('_sptemUS_weightedstat', PACKAGE = 'sptemUS', path, modelpath, metric, preStr, idStr, dateStr)
}

